// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijgjsoyjvghcwckfqfjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqZ2pzb3lqdmdoY3dja2ZxZmptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTgxMzEsImV4cCI6MjA2NTQ3NDEzMX0.J0w2H2J9cqSA5B4Me15pboXiMalCBSCD9Utxu2mnDx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);